# path to your oh-my-zsh installation
export ZSH="$HOME/.dotfiles/zsh/oh-my-zsh"

export EDITOR="vim"

# theme configuration
ZSH_THEME="bullet-train"
BULLETTRAIN_PROMPT_ORDER=(
  dir
  git
)
BULLETTRAIN_PROMPT_SEPARATE_LINE="false"

# hyphen insesitive searching; requires case sensisitve searching off 
HYPHEN_INSENSITIVE="true"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# aliases
alias repos="cd $HOME/repos"
alias tmux="env TERM=xterm-256color tmux"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
